'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const context = {};
context.globalThis = context;
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'js', 'shared', 'dnr-rules.js'), 'utf8'), context);
const rules = context.DashBridgeDnrRules.buildSessionRules(['grafana.example:8443'], [17, 23]);
assert.strictEqual(rules.length, 2);
assert.deepStrictEqual(Array.from(rules[0].condition.tabIds), [17]);
assert.deepStrictEqual(Array.from(rules[1].condition.tabIds), [23]);
assert.strictEqual(rules[0].condition.urlFilter, '||grafana.example:8443/');
assert.deepStrictEqual(Array.from(rules[0].condition.resourceTypes), ['sub_frame']);
const capped = context.DashBridgeDnrRules.buildSessionRules(['a.test', 'b.test'], [1, 2], { maxRules: 3 });
assert.strictEqual(capped.length, 3);
const plan = context.DashBridgeDnrRules.planSessionRules(['B.test', 'a.test', 'a.test'], [2, 1, 2], { maxRules: 3 });
assert.strictEqual(plan.desiredRuleCount, 4);
assert.strictEqual(plan.installedRuleCount, 3);
assert.strictEqual(plan.omittedRuleCount, 1);
assert.strictEqual(plan.truncated, true);
assert.strictEqual(plan.rules[0].condition.urlFilter, '||a.test/');
assert.deepStrictEqual(Array.from(plan.rules[0].condition.tabIds), [1]);
assert.strictEqual(context.DashBridgeDnrRules.planSessionRules([], [1]).truncated, false);
console.log('PASS Grafana DNR rules are session-scoped to DashBridge tab IDs');
